### ISSUE TITLE
[Bug]: Builds for esp32s2 are currently broken

### ISSUE THREAD

**Issue by breqdev** [meshtastic/firmware#10799]
### Category

Hardware Compatibility

### Hardware

Other

### Is this bug report about any UI (https://meshtastic.org/docs/configuration/device-uis/) component firmware?

- [ ] Meshtastic UI aka MUI
- [ ] InkHUD
- [ ] BaseUI

### Firmware Version

ad132e95 (latest commit at time of writing)

### Description

Compiling for the ESP32S2 currently results in an error relating to `USBSerial`.

This is on a fresh PlatformIO install. Compiling for other targets (ESP32S3 etc) works as expected.

I'm using the `nugget-s2-lora` target as it is the only ESP32S2 target already in the repo:

```
pio run -e nugget-s2-lora
```

### Relevant log output

```Shell
In file included from /home/breq/.platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:202,
                 from .dummy/sketch.cpp:1:
.dummy/sketch.cpp: In function 'void setup()':
/home/breq/.platformio/packages/framework-arduinoespressif32/cores/esp32/HardwareSerial.h:445:16: error: 'USBSerial' was not declared in this scope; did you mean 'Serial'?
  445 | #define Serial USBSerial
      |                ^~~~~~~~~
.dummy/sketch.cpp:4:3: note: in expansion of macro 'Serial'
    4 |   Serial.begin(115200);
      |   ^~~~~~
Compiling .pio/build/nugget-s2-lora/bt/common/osi/config.c.o
.dummy/sketch.cpp: In function 'void loop()':
/home/breq/.platformio/packages/framework-arduinoespressif32/cores/esp32/HardwareSerial.h:445:16: error: 'USBSerial' was not declared in this scope; did you mean 'Serial'?
  445 | #define Serial USBSerial
      |                ^~~~~~~~~
.dummy/sketch.cpp:8:3: note: in expansion of macro 'Serial'
    8 |   Serial.println("Hello World!");
      |   ^~~~~~
```

**Comment by breqdev** [comment]
Based on a git bisect, it seems like a5419574804709db446273c8ce5d946a3a62807c (#9122) is the first commit with a failing esp32s2 build.

**Comment by hiSandog** [comment]
The bisect to #9122 is very helpful. Since this is a compile-time regression, adding at least one ESP32S2 target such as `nugget-s2-lora` to the lightweight build matrix would probably catch it earlier than device testing. The acceptance check could simply be that `USBSerial`-related code is either guarded out for S2 or backed by the correct USB implementation for that target.

**Comment by naskoblg** [comment]
I have similar issue with the latest git commit. 

Environment: 

```
user@Latitude:~/Projects/Meshtastic/firmware$ uname -a
Linux Latitude 6.12.94+deb13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.12.94-1 (2026-06-20) x86_64 GNU/Linux
user@Latitude:~/Projects/Meshtastic/firmware$ code --version
1.126.0
7e7950df89d055b5a378379db9ee14290772148a
x64
user@Latitude:~/Projects/Meshtastic/firmware$ git branch
* develop
user@Latitude:~/Projects/Meshtastic/firmware$ git log --oneline
0eaad0873 (HEAD -> develop, origin/develop, origin/HEAD) Fix T1000-E QMA6100P I2C probing (#10713)

```

PlatformIO: Pick Project Environment -> nugget_s2_lora


pioarduino: Build -> 

```
Compiling .pio/build/nugget-s2-lora/bt/common/btc/core/btc_task.c.o
In file included from /home/user/.platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:202,
                 from .dummy/sketch.cpp:1:
.dummy/sketch.cpp: In function 'void setup()':
/home/user/.platformio/packages/framework-arduinoespressif32/cores/esp32/HardwareSerial.h:445:16: error: 'USBSerial' was not declared in this scope; did you mean 'Serial'?
  445 | #define Serial USBSerial
      |                ^~~~~~~~~
.dummy/sketch.cpp:4:3: note: in expansion of macro 'Serial'
    4 |   Serial.begin(115200);
      |   ^~~~~~
.dummy/sketch.cpp: In function 'void loop()':
/home/user/.platformio/packages/framework-arduinoespressif32/cores/esp32/HardwareSerial.h:445:16: error: 'USBSerial' was not declared in this scope; did you mean 'Serial'?
  445 | #define Serial USBSerial
      |                ^~~~~~~~~
.dummy/sketch.cpp:8:3: note: in expansion of macro 'Serial'
    8 |   Serial.println("Hello World!");
      |   ^~~~~~
Compiling .pio/build/nugget-s2-lora/bt/common/btc/profile/esp/blufi/blufi_prf.c.o
Archiving .pio/build/nugget-s2-lora/esp-idf/bootloader_support/libbootloader_support.a
Indexing .pio/build/nugget-s2-lora/esp-idf/bootloader_support/libbootloader_support.a
Compiling .pio/build/nugget-s2-lora/bt/common/btc/profile/esp/blufi/blufi_protocol.c.o
Compiling .pio/build/nugget-s2-lora/bt/common/osi/alarm.c.o
*** [.pio/build/nugget-s2-lora/.dummy/sketch.cpp.o] Error 1
======================================================== [FAILED] Took 88.72 seconds ========================================================

Environment     Status    Duration
--------------  --------  ------------
nugget-s2-lora  FAILED    00:01:28.718
=================================================== 1 failed, 0 succeeded in 00:01:28.718 ===================================================

 *  The terminal process "platformio 'run', '--environment', 'nugget-s2-lora'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task: platformio run --environment nugget-s2-lora 
```

VSCode Problems output:
```
'USBSerial' was not declared in this scope; did you mean 'Serial'?
```

**Comment by RCGV1** [comment]
I opened draft PR #10843 to address this: https://github.com/meshtastic/firmware/pull/10843\n\nOn current develop I reproduced the original failure as `USBSerial` being selected by the ESP32-S2 board defaults. Enabling TinyUSB was not sufficient because the S2 build then failed on missing TinyUSB headers, so the PR instead disables CDC-on-boot for this variant and links the matching ESP-IDF S2 `libcoexist.a` archive that the pioarduino S2 Arduino libs bundle omits.\n\nVerified with: `~/.platformio/penv/bin/pio run -e nugget-s2-lora -j1` (passed).

**Comment by RCGV1** [comment]
Split the earlier combined draft into an issue-specific draft PR: #10845 contains only the ESP32-S2/nugget build fix for this issue. Verified with `git diff --check` and `pio run -e nugget-s2-lora -j1` (pass).

**Comment by Ra2-IFV** [comment]
Breaks my dummy ESP-S3

https://community.platformio.org/t/esp32-s3-native-usb-interface-and-serial-monitor-missing-first-messages/40377/10
<table class="custom-table">
  <thead>
    <tr>
      <th>ARDUINO_USB_CDC_ON_BOOT</th>
      <th>USB_MODE</th>
      <th>UART <br>(RX/TX)</th>
      <th>USB <br>(native)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>0</td>
      <td>0</td>
      <td><strong>Serial</strong> <br> <a href="https://github.com/espressif/arduino-esp32/blob/5e19e086c43d0fa5e5a596497ff8f11a0a43f6c2/cores/esp32/HardwareSerial.h#L187" data-clicks="44" aria-label="HardwareSerial link clicked 44 times"><code>HardwareSerial</code></a></td>
      <td>n/a</td>
    </tr>
    <tr>
      <td>0</td>
      <td>1</td>
      <td><strong>Serial</strong> <br> <a href="https://github.com/espressif/arduino-esp32/blob/5e19e086c43d0fa5e5a596497ff8f11a0a43f6c2/cores/esp32/HardwareSerial.h#L187" data-clicks="44" aria-label="HardwareSerial link clicked 44 times"><code>HardwareSerial</code></a></td>
      <td><strong>USBSerial</strong> <br> <a href="https://github.com/espressif/arduino-esp32/blob/5e19e086c43d0fa5e5a596497ff8f11a0a43f6c2/cores/esp32/HWCDC.h#L43" data-clicks="84" aria-label="HWCDC link clicked 84 times"><code>HWCDC</code></a></td>
    </tr>
    <tr>
      <td>1</td>
      <td>0</td>
      <td><strong>Serial0</strong> <br> <a href="https://github.com/espressif/arduino-esp32/blob/5e19e086c43d0fa5e5a596497ff8f11a0a43f6c2/cores/esp32/HardwareSerial.h#L187" data-clicks="44" aria-label="HardwareSerial link clicked 44 times"><code>HardwareSerial</code></a></td>
      <td><strong>Serial</strong> <br> <a href="https://github.com/espressif/arduino-esp32/blob/5e19e086c43d0fa5e5a596497ff8f11a0a43f6c2/cores/esp32/USBCDC.h#L59" data-clicks="58" aria-label="USBCDC link clicked 58 times"><code>USBCDC</code></a></td>
    </tr>
    <tr>
      <td>1</td>
      <td>1</td>
      <td><strong>Serial0</strong> <br> <a href="https://github.com/espressif/arduino-esp32/blob/5e19e086c43d0fa5e5a596497ff8f11a0a43f6c2/cores/esp32/HardwareSerial.h#L187" data-clicks="44" aria-label="HardwareSerial link clicked 44 times"><code>HardwareSerial</code></a></td>
      <td><strong>USBSerial</strong> <br> <a href="https://github.com/espressif/arduino-esp32/blob/5e19e086c43d0fa5e5a596497ff8f11a0a43f6c2/cores/esp32/HWCDC.h#L43" data-clicks="84" aria-label="HWCDC link clicked 84 times"><code>HWCDC</code></a></td>
    </tr>
  </tbody>
</table>
