### PR TITLE
fix(nodedb): build the fixed-GPS userprefs path again

### LINKED ISSUE #11812: info is never declared anywhere in NodeDB::NodeDB()
https://github.com/meshtastic/firmware/blob/2dbc33e4d16da39649f9030d43d89d6206f9fb39/src/mesh/NodeDB.cpp#L705

 info is never declared anywhere in NodeDB::NodeDB().

It only compiles for builds that skip this guard, which needs USERPREFS_FIXED_GPS_LAT/LON both defined and MESHTASTIC_EXCLUDE_POSITIONDB unset.

Introduced in commit 94bb21ecc7 which added the nodePositions[...] write without noticing this scope has no info; every other write to nodePositions for "our own node" in this file uses getNodeNum() (e.g. line 1793).

Fix `nodePositions[getNodeNum()] = TypeConversions::ConvertToPositionLite(fixedGPS);`;

### PR DESCRIPTION
**Pull request by thebentern**
Fixes #11812

## What is broken

The `USERPREFS_FIXED_GPS` block in the `NodeDB` constructor holds two defects. Both only surface on vendor builds that set `USERPREFS_FIXED_GPS_LAT` and `USERPREFS_FIXED_GPS_LON`. `userPrefs.jsonc` ships those keys commented out and no CI target defines them, so this block is never compiled in this repo and neither defect was caught.

**1. Hard compile error.** `info` is not declared anywhere in the constructor. The reference is a leftover: before 94bb21ecc7 the constructor had a local `meshtastic_NodeInfoLite *info = getOrCreateMeshNode(getNodeNum());`, and the refactor removed the local while keeping the use. Any build with both fixed-GPS keys set fails with `error: 'info' was not declared in this scope`.

Because that local was initialised from `getOrCreateMeshNode(getNodeNum())`, `getNodeNum()` resolves to exactly the key `info->num` used to give. It also matches how `clearLocalPosition()` and the other own-node satellite writers address the local node. The recently added orphan sweep in #11808 exempts `self` explicitly, so a self-keyed entry is the one the pruner is built to keep.

**2. Null pointer dereference on the next line.** `setLocalPosition()` was called through the global `nodeDB`, but `main.cpp` only assigns that global after `new NodeDB` returns. Inside the constructor it is still `nullptr`, so the call stored `localPosition` through a null `this`. This one is older than the refactor, dating to #5341. Calling directly matches the sibling `setLocalPosition()` call earlier in the same constructor.

## Verification

Forcing the two user preference keys on via build flags, against the `native` target:

| | Result |
| --- | --- |
| Before this change | `error: 'info' was not declared in this scope` |
| After this change | builds and links clean |

Native test suite: 1393 of 1393 pass.

## Notes for the reviewer

Two related things I found while confirming this, deliberately **not** in this PR so the fix stays reviewable. Happy to fold either in here if you would rather.

- **The block never marks itself dirty.** `saveWhat` is finalised by the CRC comparisons above, and this block then mutates `nodePositions` (a `std::map` member, invisible to `crc32Buffer(&nodeDatabase, ...)`) plus `config.position.fixed_position`. `saveToDisk(saveWhat)` is the only save left in the constructor, so persisting the fixed position is incidental rather than guaranteed. The bad case is asymmetric: on a build that also pins a region, key generation dirties `config`, so `fixed_position = true` persists while the coordinates do not, which suppresses GPS wake permanently.
- **No CI builds any user preferences.** That is why a hard compile error survived here since May. A `coverage-*` style environment that defines a representative set of keys would close the whole class; the repo already uses that pattern elsewhere.

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed an issue where a configured fixed GPS position was not reliably saved during first-time setup.
  * Fixed persistence of related position and configuration changes so devices using a fixed GPS location retain and report their configured position correctly.

### CODE REVIEW

File: src/mesh/NodeDB.cpp [hunk 1]
```diff
@@ -708,10 +708,10 @@ NodeDB::NodeDB()
 #if !MESHTASTIC_EXCLUDE_POSITIONDB
         {
             concurrency::LockGuard guard(&satelliteMutex);
-            nodePositions[info->num] = TypeConversions::ConvertToPositionLite(fixedGPS);
+            nodePositions[getNodeNum()] = TypeConversions::ConvertToPositionLite(fixedGPS);
         }
 #endif
-        nodeDB->setLocalPosition(fixedGPS);
+        setLocalPosition(fixedGPS);
```
[the remark this answers is not in the document]
Comment (thebentern) [reply src/mesh/NodeDB.cpp:717]: Good catch, and it matches what I found while verifying this PR. Fixed in 7eba734.

I flagged each segment next to the write that dirties it rather than setting both at the end, since `nodePositions` is only touched under `!MESHTASTIC_EXCLUDE_POSITIONDB` and there is nothing to persist there when that is excluded.

One deliberate difference from the suggestion: `SEGMENT_CONFIG` is set behind `!configDecodeFailed`, matching the guard on the compare above it. Setting it unconditionally would let a degraded boot overwrite an unreadable-but-possibly-transient config with UNSET defaults, which is the failure that guard exists to prevent.

Worth noting the practical impact, since it is asymmetric rather than a plain loss: on a build that also pins a region, key generation dirties `config`, so `fixed_position = true` persisted while the coordinates did not. The next boot found no stored position, GPS wake stayed suppressed because the fixed flag was set, and the block could not re-run because it is gated on `reboot_count == 1`.

Verified with both fixed-GPS keys forced on: native builds clean, 1393/1393 native tests pass.
